name: 'frontend-radiodiagnosis-v1'

services:
  frontend:
    container_name: frontend-react
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        NODE_ENV: production
    env_file:
      - .env
    ports:
      - "${PRODUCTION_PORT}:${PRODUCTION_PORT}"
#    volumes:
#      - .:/app